name:                yahnn
version:             0.1.0.0
github:              "bstuder/yahnn"
license:             BSD3
author:              "Bruno Studer"
maintainer:          "studer.bruno@gmail.com"
copyright:           "(c) 2018 Bruno Studer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bstuder/yahnn#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -fdiagnostics-color=always
  - -fprint-expanded-synonyms
  - -fprint-typechecker-elaboration
  - -fwarn-dodgy-exports
  - -fwarn-dodgy-imports
  - -fwarn-duplicate-exports
  - -fwarn-missing-signatures
  - -fwarn-unused-binds
  - -fwarn-unused-imports
  - -fwarn-unused-matches
  - -fwarn-unused-do-bind
  - -fwarn-wrong-do-bind
  - -fwarn-warnings-deprecations
  dependencies:
    - bytestring
    - cereal
    - cereal-vector
    - random
    - vector

executables:
  yahnn-exe:
    main: Main.hs
    source-dirs: app
    default-extensions:
    - StrictData
    ghc-options:
    - -fdiagnostics-color=always
    - -fprint-expanded-synonyms
    - -fprint-typechecker-elaboration
    - -fwarn-dodgy-exports
    - -fwarn-dodgy-imports
    - -fwarn-duplicate-exports
    - -fwarn-missing-signatures
    - -fwarn-unused-binds
    - -fwarn-unused-imports
    - -fwarn-unused-matches
    - -fwarn-unused-do-bind
    - -fwarn-wrong-do-bind
    - -fwarn-warnings-deprecations
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - cereal
    - cereal-vector
    - Chart
    - Chart-cairo
    - random
    - time
    - vector
    - yahnn

tests:
  yahnn-test:
    main: Spec.hs
    source-dirs: test
    default-extensions:
    - StrictData
    ghc-options:
    - -fdiagnostics-color=always
    - -fprint-expanded-synonyms
    - -fprint-typechecker-elaboration
    - -fwarn-dodgy-exports
    - -fwarn-dodgy-imports
    - -fwarn-duplicate-exports
    - -fwarn-missing-signatures
    - -fwarn-unused-binds
    - -fwarn-unused-imports
    - -fwarn-unused-matches
    - -fwarn-unused-do-bind
    - -fwarn-wrong-do-bind
    - -fwarn-warnings-deprecations
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
    - random
    - vector
    - yahnn
