name:                yahnn
version:             0.1.0.0
github:              "bstuder/yahnn"
license:             BSD3
author:              "Bruno Studer"
maintainer:          "studer.bruno@gmail.com"
copyright:           "(c) 2018 Bruno Studer"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Development

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bstuder/yahnn#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - random 
    - vector

executables:
  convert-MNIST-exe:
    main: Convert_MNIST.hs
    source-dirs: tools
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - binary
    - cereal
    - cereal-vector
    - vector
  yahnn-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - yahnn
    - vector

tests:
  yahnn-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - QuickCheck
    - random
    - vector
    - yahnn
